spring.application.name=calculo-abn-backend

# 1. El Puerto
server.port=${PORT:8080}

# 2. Datos de conexion DUALES (H2 para local, Postgres para Render)
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:h2:mem:abn_db;DB_CLOSE_DELAY=-1}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:sa}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:}
spring.datasource.driver-class-name=${SPRING_DATASOURCE_DRIVER:org.h2.Driver}

# 3. Inicializacion
spring.jpa.defer-datasource-initialization=true
spring.jpa.hibernate.ddl-auto=${HIBERNATE_DDL:update}
spring.jpa.show-sql=true

# 4. Consola H2
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# 5. Extras
spring.jackson.serialization.fail-on-empty-beans=false
springdoc.swagger-ui.path=/swagger